/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIncidentsRouteImport } from './routes/app.incidents'
import { Route as AppLearningRouteImport } from './routes/app.learning'
import { Route as AppMemoryRouteImport } from './routes/app.memory'
import { Route as AppPredeployRouteImport } from './routes/app.predeploy'
import { Route as AppSettingsRouteImport } from './routes/app.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/app/incidents',
  path: '/app/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLearningRoute = AppLearningRouteImport.update({
  id: '/app/learning',
  path: '/app/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/app/memory',
  path: '/app/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPredeployRoute = AppPredeployRouteImport.update({
  id: '/app/predeploy',
  path: '/app/predeploy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/learning': typeof AppLearningRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/predeploy': typeof AppPredeployRoute
  '/app/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/learning': typeof AppLearningRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/predeploy': typeof AppPredeployRoute
  '/app/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/learning': typeof AppLearningRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/predeploy': typeof AppPredeployRoute
  '/app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/incidents'
    | '/app/learning'
    | '/app/memory'
    | '/app/predeploy'
    | '/app/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/incidents'
    | '/app/learning'
    | '/app/memory'
    | '/app/predeploy'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/app/incidents'
    | '/app/learning'
    | '/app/memory'
    | '/app/predeploy'
    | '/app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppLearningRoute: typeof AppLearningRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppPredeployRoute: typeof AppPredeployRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/app/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/learning': {
      id: '/app/learning'
      path: '/app/learning'
      fullPath: '/app/learning'
      preLoaderRoute: typeof AppLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/memory': {
      id: '/app/memory'
      path: '/app/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/predeploy': {
      id: '/app/predeploy'
      path: '/app/predeploy'
      fullPath: '/app/predeploy'
      preLoaderRoute: typeof AppPredeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppLearningRoute: AppLearningRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppPredeployRoute: AppPredeployRoute,
  AppSettingsRoute: AppSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
